spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?characterEncoding=utf-8&useSSL=false
    username: root
    password: jsbbsj
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    port: 5672
    password: guest
    username: guest
    addresses: 127.0.0.1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
